<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="$(SolutionDir)/Tixl.props" />
    <PropertyGroup>
        <TargetFramework>$(TixlNetFrameworkVersion)</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Deterministic>true</Deterministic>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Core\Core.csproj" />
    </ItemGroup>
</Project>
